(function(){
  'use strict';
  const $ = (id) => document.getElementById(id);
  const css = `
  .agent-cockpit{margin:0 0 12px;background:linear-gradient(180deg,rgba(53,215,196,.09),rgba(239,74,86,.05)),#16171d;border:1px solid rgba(255,255,255,.16);border-radius:18px;padding:12px;display:grid;grid-template-columns:.9fr 1.15fr .95fr;gap:10px;box-shadow:0 30px 70px -30px rgba(0,0,0,.75)}
  @media(max-width:900px){.agent-cockpit{grid-template-columns:1fr}}
  .agent-card{background:rgba(29,31,39,.88);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:10px 12px;min-width:0}.agent-title{display:flex;align-items:center;justify-content:space-between;gap:8px;font-family:'JetBrains Mono',monospace;font-size:.62rem;font-weight:800;letter-spacing:.7px;color:#ffb84d;margin-bottom:8px}.agent-badge{font-family:'JetBrains Mono',monospace;font-size:.58rem;font-weight:800;letter-spacing:.6px;border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:2px 7px;color:#8b8d99;background:rgba(255,255,255,.035);white-space:nowrap}.agent-badge.on{color:#35d7c4;border-color:#35d7c4;background:rgba(53,215,196,.15)}
  .agent-row{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:7px 0}.agent-row label{font-size:.68rem;color:#8b8d99;font-weight:700;white-space:nowrap}.agent-select{min-width:130px;flex:1;background:#262832;color:#eef0f4;border:1px solid rgba(255,255,255,.15);border-radius:9px;padding:6px 8px;font-family:'Cairo',system-ui,sans-serif;font-size:.72rem}.agent-row input[type=range]{flex:1}.agent-pill{font-family:'JetBrains Mono',monospace;font-size:.66rem;color:#35d7c4;min-width:42px;text-align:left}.agent-metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px}.agent-metric{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08);border-radius:10px;padding:8px;min-width:0}.agent-metric .k{font-size:.62rem;color:#565964;font-family:'JetBrains Mono',monospace;letter-spacing:.4px}.agent-metric .v{font-size:.78rem;color:#eef0f4;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;unicode-bidi:plaintext}.agent-reason{font-size:.72rem;color:#8b8d99;line-height:1.55;unicode-bidi:plaintext}.agent-reason b{color:#eef0f4}.agent-actions{display:flex;flex-direction:column;gap:5px;max-height:145px;overflow:auto}.agent-action{display:grid;grid-template-columns:54px 1fr;gap:7px;align-items:start;font-size:.69rem;color:#8b8d99;line-height:1.35;padding:6px 7px;border-radius:8px;background:rgba(255,255,255,.032)}.agent-action strong{font-family:'JetBrains Mono',monospace;color:#35d7c4;font-size:.58rem;letter-spacing:.4px}.agent-action.warn strong{color:#ffb84d}.agent-action.danger strong{color:#ef4a56}.agent-ai-mark{box-shadow:0 0 0 1px #ffb84d,0 0 18px rgba(255,184,77,.22)!important;border-color:#ffb84d!important;filter:brightness(1.18)}
  .agent-deck-badge{position:absolute;top:-8px;inset-inline-start:12px;z-index:2;font-family:'JetBrains Mono',monospace;font-size:.56rem;font-weight:900;letter-spacing:.6px;padding:2px 7px;border-radius:999px;border:1px solid rgba(255,255,255,.16);background:#16171d;color:#565964}.deck{position:relative}.agent-deck-badge.live-a{color:#35d7c4;border-color:#35d7c4}.agent-deck-badge.live-b{color:#ef4a56;border-color:#ef4a56}.agent-deck-badge.next{color:#ffb84d;border-color:#ffb84d}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  function html(){return `<section class="agent-cockpit" id="agentCockpit"><div class="agent-card"><div class="agent-title"><span>AI DJ AGENT</span><span class="agent-badge" id="agentBadge">STANDBY</span></div><div class="agent-row"><label>الشخصية</label><select class="agent-select" id="agentMode"><option value="smooth">Smooth DJ</option><option value="club">Club DJ</option><option value="creative" selected>Creative DJ</option><option value="safe">Safe DJ</option></select></div><div class="agent-row"><label>تحكم البوت</label><input type="range" id="agentLevel" min="0" max="100" step="5" value="100"><span class="agent-pill" id="agentLevelText">100%</span></div><div class="agent-reason" id="agentModeExplain">تحكم كامل بكل الديكات، الفيدرز، EQ، FX، Loops، Pads، والـSampler حسب الموسيقى.</div></div><div class="agent-card"><div class="agent-title"><span>AI BRAIN</span><span class="agent-badge on" id="agentBrainBadge">FULL CONTROL</span></div><div class="agent-metrics"><div class="agent-metric"><div class="k">LIVE</div><div class="v" id="agentLive">—</div></div><div class="agent-metric"><div class="k">NEXT</div><div class="v" id="agentNext">—</div></div><div class="agent-metric"><div class="k">STRATEGY</div><div class="v" id="agentStrategy">—</div></div><div class="agent-metric"><div class="k">ARC</div><div class="v" id="agentArc">—</div></div></div><div class="agent-reason" id="agentReason" style="margin-top:8px">اضغط AI TAKE OVER وأنا بمسك الجهاز كاملًا.</div></div><div class="agent-card"><div class="agent-title"><span>AI ACTIONS</span><span class="agent-badge" id="agentActionCount">0</span></div><div class="agent-actions" id="agentActions"><div class="agent-action"><strong>READY</strong><span>جاهز أستلم كل شيء.</span></div></div></div></section>`}
  const next=document.getElementById('nextMixPanel')||document.querySelector('.mixer'); if(next){next.insertAdjacentHTML('afterend',html());}
  [['A','.deck-a'],['B','.deck-b']].forEach(([k,sel])=>{const d=document.querySelector(sel); if(d&&!document.getElementById('agentDeck'+k)){d.insertAdjacentHTML('afterbegin',`<div class="agent-deck-badge" id="agentDeck${k}">IDLE</div>`);}});
  const profiles={smooth:'انتقالات طويلة وناعمة، FX قليل، تغييرات طاقة تدريجية.',club:'Bass swap أوضح، Drop swaps أكثر، طاقة أعلى.',creative:'تحكم كامل: لووبات، سامبلر من نفس الأغنية، FX، Hot Cues، وBass swaps حسب الموسيقى.',safe:'أقل مخاطرة: يتجنب تصادم الغناء، FX محدود، انتقالات مضمونة.'};
  let mode='creative', level=100, actions=[], lastTransitionKey='', armedCreative=false;
  function dbg(){return window.__djDebug||null} function auto(){const d=dbg(); return d&&d.autoDj&&d.autoDj.state?d.autoDj.state:null}
  function log(label,text,kind){actions.unshift({label,text,kind:kind||''}); actions=actions.slice(0,9); renderActions();}
  function renderActions(){const box=$('agentActions'); if(!box)return; $('agentActionCount').textContent=String(actions.length); box.innerHTML=actions.map(a=>`<div class="agent-action ${a.kind}"><strong>${a.label}</strong><span>${a.text}</span></div>`).join('')||'<div class="agent-action"><strong>READY</strong><span>جاهز.</span></div>';}
  function mark(el){if(!el)return; el.classList.add('agent-ai-mark'); clearTimeout(el.__agentMark); el.__agentMark=setTimeout(()=>el.classList.remove('agent-ai-mark'),800)}
  function setRange(id,val){const el=$(id); if(!el)return; el.value=String(val); el.dispatchEvent(new Event('input',{bubbles:true})); mark(el)}
  function click(id){const el=$(id); if(el&&!el.disabled){mark(el); el.click();}}
  function setEq(k,band,val){setRange((band==='high'?'eqHi':band==='mid'?'eqMid':band==='low'?'eqLow':'color')+k,val)}
  function fx(k,name){const d=dbg(); if(d&&d.actions){d.actions.toggleFx(k,name); mark((k==='A'?$('padsA'):$('padsB')));}}
  function loop(k,beats){const d=dbg(); if(d&&d.actions){d.actions.toggleLoopSize(k,beats||4); mark((k==='A'?$('padsA'):$('padsB')));}}
  function sampler(k,action,index){const d=dbg(); if(!d||!d.actions)return; d.actions.setPadMode(k,'sampler'); if(action==='capture')d.actions.samplerAction(k,index||0); if(action==='play'){const slot=d.decks[k].samplerSlots[index||0]; if(slot) { const src=d.actions.samplerAction(k,index||0); }} mark(k==='A'?$('padsA'):$('padsB'));}
  function statusFor(k,a,d){if(a&&a.liveKey===k&&a.transition)return'MIXING'; if(a&&a.liveKey===k)return'LIVE'; if(a&&a.nextTrack&&a.nextTrack.key===k)return'NEXT'; const m=d&&d.decks&&d.decks[k]&&d.decks[k].meta; return m?(m.playing?'PLAYING':'CUED'):'IDLE'}
  function deckName(d,k){const m=d&&d.decks&&d.decks[k]&&d.decks[k].meta; return m&&m.track?m.track.name:'—'}
  function actOnTransition(a,d){if(!a||!a.transition||level<75)return; const t=a.transition; const key=t.fromKey+'>'+t.toKey+':'+Math.round(t.startedAt||0); if(key!==lastTransitionKey){lastTransitionKey=key; armedCreative=false; log('MIX','AI يمسك الفيدرز والـEQ والفلتر أثناء الانتقال من Deck '+t.fromKey+' إلى '+t.toKey+'.','warn')}
    const dur=Math.max(.5,t.duration||1); const p=Math.max(0,Math.min(1,((d.now?d.now():0)-(t.startedAt||0))/dur));
    if(mode==='club'||mode==='creative'){setEq(t.fromKey,'filter',-p*(mode==='creative'?0.7:0.45)); setEq(t.toKey,'filter',Math.max(0,(1-p)*0.22));}
    if(mode==='creative'&&level>=100&&!armedCreative&&p>.18){armedCreative=true; try{sampler(t.fromKey,'capture',0); log('PAD','أخذت سامبل قصير من نفس الأغنية لاستخدامه كـfill إبداعي.','warn'); setTimeout(()=>{if(auto()&&auto().on){sampler(t.fromKey,'play',0); log('PAD','شغّلت السامبل أثناء الميكس.')}},Math.max(700,dur*330));}catch(e){}}
    if(mode==='club'&&p>.55&&p<.62){fx(t.fromKey,'echo'); log('FX','Echo خفيف للخروج بنظافة.','warn')}
  }
  function render(){const d=dbg(),a=auto(); const on=!!(a&&a.on); const badge=$('agentBadge'); if(badge){badge.textContent=on?'ACTIVE':'STANDBY'; badge.classList.toggle('on',on)} const brain=$('agentBrainBadge'); if(brain){brain.textContent=level>=75?'FULL CONTROL':level>=50?'CONFIRM MODE':level>=25?'SUGGEST ONLY':'MANUAL'; brain.classList.toggle('on',level>=75)} if($('agentLevelText'))$('agentLevelText').textContent=level+'%'; if($('agentModeExplain'))$('agentModeExplain').textContent=profiles[mode]||profiles.creative; if($('agentLive'))$('agentLive').textContent=a&&a.liveKey?('Deck '+a.liveKey+' · '+deckName(d,a.liveKey)):'—'; if($('agentNext'))$('agentNext').textContent=a&&a.nextTrack?('Deck '+a.nextTrack.key+' · '+a.nextTrack.track.name):(a&&a.idleKey?'Deck '+a.idleKey:'—'); if($('agentStrategy'))$('agentStrategy').textContent=a&&a.nextTrack&&a.nextTrack.plan?a.nextTrack.plan.strategy.name:(a&&a.transition?a.transition.strategy.name:mode.toUpperCase()); if($('agentArc'))$('agentArc').textContent=a&&a.arc?a.arc.phase:'—'; if($('agentReason'))$('agentReason').innerHTML=on?'<b>AI مستلم:</b> أراقب BPM، المقام، الطاقة، الغناء، الباص، والـphrase boundaries وأتحكم بالـUI نفسه.':'<b>Manual:</b> اضغط AI TAKE OVER حتى أستلم.'; ['A','B'].forEach(k=>{const el=$('agentDeck'+k); if(!el)return; const st=statusFor(k,a,d); el.textContent=st; el.className='agent-deck-badge '+(st==='LIVE'||st==='MIXING'?(k==='A'?'live-a':'live-b'):st==='NEXT'?'next':'')}); actOnTransition(a,d); requestAnimationFrame(render)}
  $('agentMode')&&$('agentMode').addEventListener('change',e=>{mode=e.target.value; log('MODE','شخصية البوت: '+mode+'.','warn')});
  $('agentLevel')&&$('agentLevel').addEventListener('input',e=>{level=parseInt(e.target.value,10)||0; log('LEVEL','مستوى التحكم الآن '+level+'%.',level>=75?'warn':'')});
  const btn=$('autoDjBtn'); if(btn){btn.textContent='AI TAKE OVER'; btn.addEventListener('click',()=>{setTimeout(()=>{const a=auto(); if(a&&a.on)log('ON','AI DJ Agent استلم الجهاز كاملًا: Decks / EQ / FX / Loops / Pads.','warn'); else log('MANUAL','TAKE CONTROL: أوقفت كل الأتمتة وتركت الصوت والقيم كما هي.','danger')},60)},{capture:true});}
  window.__agentTakeover={setMode:m=>{mode=m;},setLevel:v=>{level=v;},log,click,setEq,fx,loop,sampler};
  render();
})();
